version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nps-widget-postgres
    environment:
      POSTGRES_DB: nps_widget_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
